name: Deploy Facturacion to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # Configurar Maven para GitHub Packages
      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.TOKEN_MAVEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Java project
        run: |
          cd facturacion
          mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/mcsv-facturacion:${{ github.sha }}
          cd facturacion
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          cd facturacion
          IMAGE=${{ secrets.DOCKER_USERNAME }}/mcsv-facturacion:${{ github.sha }}
          sed -i "s|IMAGE_TAG|$IMAGE|g" FacturacionDeploy.yaml
          echo "Deploying image: $IMAGE"
          kubectl apply -f FacturacionDeploy.yaml
          kubectl apply -f FacturacionService.yaml
          kubectl rollout status deployment/facturacion-deploy --timeout=180s
